### ISSUE TITLE
panic when processor read_from_server payload len is greater than 65535

### ISSUE THREAD

**Issue by hminbdxxxx** [JonForShort/android-local-vpn#2]
Hi, thank you for your great project. I am testing android-local-vpn with an app receiving udp packets, but the app keeps crashing. I got the app log from logcat and found it crashed because of the rust lib panic.

```
02-28 15:58:01.447  2763 31797 V nativeVpn: core::vpn::processor: handling events, count=1
02-28 15:58:01.447  2763 31797 V nativeVpn: core::vpn::processor: handle server event read, session=SessionInfo { source: 10.0.0.2:42650, destination: xx.xx.xx.xx:18730, transport_protocol: Udp, internet_protocol: Ipv4 }
02-28 15:58:01.447  2763 31797 V nativeVpn: core::vpn::processor: read from server, session=SessionInfo { source: 10.0.0.2:42650, destination: xx.xx.xx.xx:18730, transport_protocol: Udp, internet_protocol: Ipv4 }
02-28 15:58:01.448  2763 31797 V nativeVpn: core::vpn::processor: finished read from server, session=SessionInfo { source: 10.0.0.2:42650, destination: xx.xx.xx.xx:18730, transport_protocol: Udp, internet_protocol: Ipv4 }
02-28 15:58:01.448  2763 31797 V nativeVpn: core::vpn::processor: write to smoltcp, session=SessionInfo { source: 10.0.0.2:42650, destination: xx.xx.xx.xx:18730, transport_protocol: Udp, internet_protocol: Ipv4 }
02-28 15:58:01.448  2763 31797 V nativeVpn: smoltcp::socket::udp: udp:xx.xx.xx.xx:18730:10.0.0.2:42650: buffer to send 68601 octets
02-28 15:58:01.452  2763 31797 V nativeVpn: core::vpn::processor: finished write to smoltcp, session=SessionInfo { source: 10.0.0.2:42650, destination: xx.xx.xx.xx:18730, transport_protocol: Udp, internet_protocol: Ipv4 }
02-28 15:58:01.452  2763 31797 V nativeVpn: core::vpn::processor: write to tun
02-28 15:58:01.452  2763 31797 V nativeVpn: smoltcp::socket::udp: udp:xx.xx.xx.xx:18730:xx.xx.xx.xx:18730: sending 68601 octets
02-28 15:58:01.452  2763 31797 E nativeVpn: vpn::android: *** PANIC [PanicInfo { payload: Any { .. }, message: Some(source slice length (68601) does not match destination slice length (3065)), location: Location { file: "xxx\\smoltcp-0.8.2\\src\\iface\\interface.rs", line: 423, col: 27 }, can_unwind: true }]
```

Seems everytime when panic occur, udp buffer size is greater than 65535, and the difference between src slice and dst slice is always 65536. I'm new to rust, I guess it's because the max IP packet size is 65535? Is there any solution to fix this problem? Thank you.

**Comment by JonForShort** [comment]
Thanks @hminbdxxxx for reporting this issue.  I'll work on a fix.  Yes I agree.  It seems that the packet size is bigger than expected.

**Comment by hminbdxxxx** [comment]
Hi Jon, I think the current implemention reads multiple udp datagrams and pushes them into serssion.buffers, then writes multiple datagrams to smoltcp socket, while udp socket can only accept one datagram. Even if the packet size panic does not occur, I guess writing multiple udp datagrams into one will still cause unexpected error. So I think the `Buffers` struct should be `VecDeque<Vec<u8>>`  when it's udp. What is your opinion?

I created a PR, I tested on my device and no more panic. I am not experienced in rust, so could you take a look?

Thanks for your awesome project again!

**Comment by JonForShort** [comment]
Thanks @hminbdxxxx for writing this up :) I'll try to take a look at this over the weekend.
