### ISSUE TITLE
Unable to run main.rs from host

### ISSUE THREAD

**Issue by RomanSter** [JonForShort/android-local-vpn#3]
rustc 1.67.1 (d5a82bbd2 2023-02-07)
cargo 1.67.1 (8ecd4f20a 2023-01-10)
MacBook Pro MacOS Ventura 13.0

I did cargo install from the core folder, then cargo run from the host folder.

While trying to run the host folder main.rs I get the following errors:

`error[E0432]: unresolved import `smoltcp::phy::TunTapInterface`
  --> src/main.rs:31:28
   |
31 | use smoltcp::phy::{Medium, TunTapInterface};
   |                            ^^^^^^^^^^^^^^^ no `TunTapInterface` in `phy`

error[E0425]: cannot find value `SO_BINDTODEVICE` in crate `libc`
  --> src/main.rs:94:19
   |
94 |             libc::SO_BINDTODEVICE,
   |                   ^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find function `__errno_location` in crate `libc`
   --> src/main.rs:100:42
    |
100 |         let error_code = unsafe { *libc::__errno_location() as i32 };
    |                                          ^^^^^^^^^^^^^^^^ not found in `libc`

warning: unused import: `std::os::unix::io::AsRawFd`
  --> src/main.rs:33:5
   |
33 | use std::os::unix::io::AsRawFd;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

Some errors have detailed explanations: E0425, E0432.
For more information about an error, try `rustc --explain E0425`.
warning: `main` (bin "main") generated 1 warning
error: could not compile `main` due to 3 previous errors; 1 warning emitted
`

Am I even attempting to run it correctly?

**Comment by JonForShort** [comment]
Hi @RomanSter, there are two ways you can run this project.  If you want to test it locally on your host machine, you just need to build the project from the `./source/host` directory.  You can build the project by running the command, `cargo build`.  Once the build completes, you can run the binary using the command, 

`RUST_LOG=trace ./source/host/target/debug/main --tun <tun interface> --out <ethernet interface>`

I haven't tested it on a Mac but looking at your errors, it might be a platform incompatibility issue? I am only testing on a Linux machine right now.

The other way to run this project is on Android.  You just need to go to the `./source/android` directory and run the command, `./gradlew build`.  This should produce the APK file in `./source/android/app/build/outputs/` and the AAR in `./source/android/vpn/build/outputs/aar`.

I am currently using rust version `1.65.0`.  It should work with newer rust versions though.

Hope this helps.

**Comment by RomanSter** [comment]
Thank you, yeah the problem is that smoltcp does not expose the TUNTAPInterface unless you are running it from linux/android.

**Comment by RomanSter** [comment]
One question, I run the host with these inputs (from a docker container): "tun0" as tun and "eth0" as out, the program runs well. when i exec the container and check ifconfig i cannot see the tun0 created.
do you have tun0 created when you run it?

**Comment by RomanSter** [comment]
I managed to run the host from a ubuntu vm, its runnig but it doesn't seem like the tun interface is created. 
(I don't see the interface while checking with `ifconfig` .

the last log I see is `registering event source with poller: token=Token(0), interests=READABLE`
Do you think I missed something? I run it using:

RUST_LOG=trace ./source/host/target/debug/main --tun tun0 --out enp0s3

**Comment by JonForShort** [comment]
@RomanSter , oh you will need to create a tun interface so that it can bind to it.  You should see it when you use the command `ifconfig`.

Please have a look at the script below for how I create the tun interface.

https://github.com/JonForShort/android-local-vpn/blob/master/scripts/add-tun.sh

**Comment by RomanSter** [comment]
That makes sense. I thought the code generates the tun interface for me heh, thank you for helping out!
